name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare backend resource
      run: docker run  --rm -d --name breeze-be --network host redis:alpine3.16
    - uses: actions/checkout@main
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
